version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/table.sql:/docker-entrypoint-initdb.d/table.sql
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL_FILE: /run/secrets/database_url
      SECRECT_KEY_FILE: /run/secrets/secret_key
    secrets:
      - database_url
      - secret_key
    networks:
      - app-network
  web:
    build:
      context: .
    # To run with --reload in development, we override the CMD in Dockerfile with following command
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # Volume mount is used for development and is not required in staging or production
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    # .env is not provided in production and instead ./secrets/ are used
    env_file: .env
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      SECRET_KEY: ${DB_SECRET_KEY}
    restart: always
