version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - APP_ENV=development
    restart: always

  staging:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    environment:
      - APP_ENV=staging
    restart: always

  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    environment:
      - APP_ENV=production
    restart: always
