version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      DATABASE_URL_FILE: /run/secrets/database_url
      SECRECT_KEY_FILE: /run/secrets/secret_key
    secrets:
      - database_url
      - secret_key
    networks:
      - app-network

  web:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

secrets:
  database_url:
    file: ./secrets/database_url.txt
  secret_key:
    file: ./secrets/secret_key.txt

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
