"""updated the date column name to ohlcvdatetime

Revision ID: 15bd18bac45d
Revises: 5f1fc6f3d3d0
Create Date: 2024-06-10 20:10:41.831978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15bd18bac45d'
down_revision: Union[str, None] = '5f1fc6f3d3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yahoo_1d730day', sa.Column('ohlcvdatetime', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('_yahoo_1d730day_ticker_date_uc', 'yahoo_1d730day', type_='unique')
    op.create_unique_constraint('_yahoo_1d730day_ticker_date_uc', 'yahoo_1d730day', ['ticker', 'ohlcvdatetime'])
    op.drop_column('yahoo_1d730day', 'date')
    op.add_column('yahoo_1wk_maxdays', sa.Column('ohlcvdatetime', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('_yahoo_1wk_maxdays_ticker_date_uc', 'yahoo_1wk_maxdays', type_='unique')
    op.create_unique_constraint('_yahoo_1wk_maxdays_ticker_date_uc', 'yahoo_1wk_maxdays', ['ticker', 'ohlcvdatetime'])
    op.drop_column('yahoo_1wk_maxdays', 'date')
    op.add_column('yahoo_30min60day', sa.Column('ohlcvdatetime', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('_yahoo_30min60day_ticker_date_uc', 'yahoo_30min60day', type_='unique')
    op.create_unique_constraint('_yahoo_30min60day_ticker_date_uc', 'yahoo_30min60day', ['ticker', 'ohlcvdatetime'])
    op.drop_column('yahoo_30min60day', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yahoo_30min60day', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('_yahoo_30min60day_ticker_date_uc', 'yahoo_30min60day', type_='unique')
    op.create_unique_constraint('_yahoo_30min60day_ticker_date_uc', 'yahoo_30min60day', ['ticker', 'date'])
    op.drop_column('yahoo_30min60day', 'ohlcvdatetime')
    op.add_column('yahoo_1wk_maxdays', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('_yahoo_1wk_maxdays_ticker_date_uc', 'yahoo_1wk_maxdays', type_='unique')
    op.create_unique_constraint('_yahoo_1wk_maxdays_ticker_date_uc', 'yahoo_1wk_maxdays', ['ticker', 'date'])
    op.drop_column('yahoo_1wk_maxdays', 'ohlcvdatetime')
    op.add_column('yahoo_1d730day', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('_yahoo_1d730day_ticker_date_uc', 'yahoo_1d730day', type_='unique')
    op.create_unique_constraint('_yahoo_1d730day_ticker_date_uc', 'yahoo_1d730day', ['ticker', 'date'])
    op.drop_column('yahoo_1d730day', 'ohlcvdatetime')
    # ### end Alembic commands ###
