"""Added psu listing model

Revision ID: 3e0528c2bee6
Revises: 700ebfdc3439
Create Date: 2024-06-01 11:46:58.235200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0528c2bee6'
down_revision: Union[str, None] = '700ebfdc3439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psu_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psu_listing')
    # ### end Alembic commands ###
