"""Added yahoo data tables and modified daily_stock_filter to have provider col

Revision ID: 577b019db658
Revises: 3e0528c2bee6
Create Date: 2024-06-08 23:17:12.503431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577b019db658'
down_revision: Union[str, None] = '3e0528c2bee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yahoo_1d730day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividends', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_splits', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('repaired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='_yahoo_1d730day_ticker_date_uc')
    )
    op.create_table('yahoo_1wk_maxdays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividends', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_splits', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('repaired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='_yahoo_1wk_maxdays_ticker_date_uc')
    )
    op.create_table('yahoo_30min60day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividends', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_splits', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('repaired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='_yahoo_30min60day_ticker_date_uc')
    )
    op.add_column('daily_stock_filter', sa.Column('provider', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stock_filter', 'provider')
    op.drop_table('yahoo_30min60day')
    op.drop_table('yahoo_1wk_maxdays')
    op.drop_table('yahoo_1d730day')
    # ### end Alembic commands ###
