"""Updated the ohlcv tables for longer ticker names

Revision ID: 5f1fc6f3d3d0
Revises: 577b019db658
Create Date: 2024-06-10 09:40:14.296541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1fc6f3d3d0'
down_revision: Union[str, None] = '577b019db658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yahoo_1d730day', 'ticker',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('yahoo_1d730day', 'adjusted_close')
    op.alter_column('yahoo_1wk_maxdays', 'ticker',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('yahoo_1wk_maxdays', 'adjusted_close')
    op.alter_column('yahoo_30min60day', 'ticker',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('yahoo_30min60day', 'adjusted_close')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yahoo_30min60day', sa.Column('adjusted_close', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('yahoo_30min60day', 'ticker',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.add_column('yahoo_1wk_maxdays', sa.Column('adjusted_close', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('yahoo_1wk_maxdays', 'ticker',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.add_column('yahoo_1d730day', sa.Column('adjusted_close', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('yahoo_1d730day', 'ticker',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
