"""Added index listing model

Revision ID: 700ebfdc3439
Revises: 3cc131d00f29
Create Date: 2024-05-30 15:16:42.895457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700ebfdc3439'
down_revision: Union[str, None] = '3cc131d00f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_listing_id'), 'index_listing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_index_listing_id'), table_name='index_listing')
    op.drop_table('index_listing')
    # ### end Alembic commands ###
