# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
import pandas as pd

chrome_driver_executable_path = ChromeDriverManager().install()
service = Service(executable_path=chrome_driver_executable_path)

options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=options, service=service)
tickers = []


driver.get("https://sg.finance.yahoo.com/quote/%5ENSEI/components/")
driver.set_window_size(1854, 1031)
WebDriverWait(driver, 10).until(
    expected_conditions.presence_of_element_located(
        (By.XPATH, '//div[@id="Main"]//tr[30]//a')
    )
)
for i in range(1, 31):
    tickers.append(driver.find_element(By.XPATH, f'//div[@id="Main"]//tr[{i}]//a').text)
print("{}".format(tickers))

driver.quit()

data = {
    "ticker": tickers,
    "provider": ["YAHOO"] * len(tickers),
    "index": ["^NSEI"] * len(tickers),
}
df = pd.DataFrame(data)
df.to_csv("assets/Nifty50-Tickers.csv", index=False)
